# action.yaml
name: 'Helm Chart Tree Renderer'
description: 'A Github Action that takes an input and returns directory of rendered templates'
inputs:
  environment:
    description: 'Environment to render the templates for'
    required: true
    default: 'dev'
  directory_path:
    description: 'e.g. /helm/'
    required: true
  rendered_path:
    description: 'e.g. /rendered/'
    default: '/rendered/'
  pattern:
    description: 'Pattern to match the files'    
    default: "helm"
  chart:
    description: 'Chart to render'
    required: true
outputs:
  rendered_templates:
    description: 'Square of the input'
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.get-results.outputs.jobs }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: install helm
      uses: azure/setup-helm@v4.2.0

    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
          echo "INPUT_ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
          echo "INPUT_DIRECTORY=${{ inputs.directory_path }}" >> $GITHUB_ENV
          echo "INPUT_PATTERN=${{ inputs.pattern }}" >> $GITHUB_ENV
          echo "INPUT_RENDERED_DIR=${{ inputs.rendered_path }}" >> $GITHUB_ENV
          echo "INPUT_CHART=${{ inputs.chart }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch the number's square
      id: get-results
      run: python src/traverse.py
      shell: bash