# action.yaml
name: "Helm Chart Tree Renderer"
description: "A Github Action that takes an input and returns directory of rendered templates"
inputs:
  environment:
    description: "Environment to render the templates for"
    required: true
    default: "dev"
  directory_path:
    description: "e.g. /helm/"
    required: true
  rendered_path:
    description: "e.g. /rendered/"
    default: "/rendered/"
  pattern:
    description: "Pattern to match the files"
    default: "helm"
  chart:
    description: "Chart to render"
    required: true
outputs:
  rendered_templates:
    description: "rendered charts records"
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.get-results.outputs.jobs }}
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: install helm
      uses: azure/setup-helm@v4.2.0

    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Pass env to Shell
      run: echo "INPUT_ENVIRONMENT=${{ inputs.environment }}" >> $GITHUB_ENV
      shell: bash
    - name: Pass dir to Shell
      run: echo "INPUT_DIRECTORY=${{ inputs.directory_path }}" >> $GITHUB_ENV
      shell: bash
    - name: Pass pattern to Shell
      shell: bash
      run: echo "INPUT_PATTERN=${{ inputs.pattern }}" >> $GITHUB_ENV
    - name: Pass rendered_path to Shell
      run: echo "INPUT_RENDERED_PATH=${{ inputs.rendered_path }}" >> $GITHUB_ENV
      shell: bash
    - name: Pass chart to Shell
      shell: bash
      run: echo "INPUT_CHART=${{ inputs.chart }}" >> $GITHUB_ENV
    - name: Fetch rendered list
      id: get-results
      run: python ${{ github.action_path }}/src/traverse.py
      shell: bash
