# action.yaml
name: "Helm Chart Tree Renderer"
description: "A Github Action that takes an input and returns directory of rendered templates"
inputs:
  directory:
    description: "Path to the directory containing the Helm chart"
    required: true
  debug:
    description: "Enable debug mode"
    required: false
    default: "false"

outputs:
  rendered_templates:
    description: "rendered charts records"
    # need to specify the extra `value` field for `composite` actions
    value: ${{ steps.get-results.outputs.jobs }}
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: install helm
      uses: azure/setup-helm@v4.2.0

    - name: Install Dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Pass directory to Shell
      run: echo "HELM_TEMPLATE_PROCESSOR_DIRECTORY=${{ inputs.directory }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch rendered list
      id: get-results
      run: python ${{ github.action_path }}/src/cli.py
      shell: bash
